String.prototype.removeAccents = function(){
    var t = this,
    a = {
        'œ' : 'oe',
        'Œ' : 'Oe',
        'æ' : 'ae',
        'Æ' : 'Ae',
        '[ÀÁÂÃÄÅAAA?????????????A]' : 'A',
        '[àáâãäåaaa?????????????a]' : 'a',
        '[ÇCCCC]' : 'C',
        '[çcccc]' : 'c',
        '[ĞDĞ]' : 'D',
        '[dd]' : 'd',
        '[ÈÉÊËEEEEE????????]' : 'E',
        '[èéêëeeeee????????]' : 'e',
        '[GGGG]' : 'G',
        '[gggg]' : 'g',
        '[HH]' : 'H',
        '[hh]' : 'h',
        '[ÌÍÎÏIIIIII??]' : 'I',
        '[ìíîïiiiiii??]' : 'i',
        'J' : 'J',
        'j' : 'j',
        'K' : 'K',
        'k' : 'k',
        '[LLL?L]' : 'L',
        '[lll?l]' : 'l',
        '[ÑNNN]' : 'N',
        '[ñnnn?]' : 'n',
        '[ÒÓÔÕÖØOOOOO?????????????]' : 'O',
        '[òóôõöøooooo?????????????ğ]' : 'o',
        '[RRR]' : 'R',
        '[rrr]' : 'r',
        '[SSSŠ]' : 'S',
        '[sssš]' : 's',
        '[TTT]' : 'T',
        '[ttt]' : 't',
        '[ÙÚÛÜUUUUUUUUUUUU???????]' : 'U',
        '[ùúûüuuuuuuuuuuuu???????]' : 'u',
        '[W???]' : 'W',
        '[w???]' : 'w',
        '[İYŸ????]' : 'Y',
        '[ıÿy????]' : 'y',
        '[ZZ]' : 'Z',
        '[zz]' : 'z'
    };
    for(var i in a){
        t = t.replace(new RegExp(i, "g"), a[i]);
    }
    return t;
};
