using System;

namespace ConsoleApplication1
{
/*
    The rules governing partial methods state that they:

    1. Must be declared inside a partial class.
    2. Must contain the keyword partial followed by the keyword void.
    3. Cannot be marked as extern
    4. Can be marked static or unsafe
    5. Can be generic
    6. Can have ref parameters, but not out parameters
    7. Cannot be referenced as a delegate until they are implemented
    8. Cannot have access modifiers such as public, private or internal. Partial methods are implicitly marked as private. This means they cannot be called from outside the partial class, and cannot be declared as virtual.
*/
    // Assume this class is autogenerated
    public partial class MyPartialClass
    {
        partial void MyPartialMethod();

        public void CallPartialMethod()
        {
            MyPartialMethod();
        }
    }

    // Assume this class is written by hand
    public partial class MyPartialClass
    {
        partial void MyPartialMethod()
        {
            Console.WriteLine("Second half");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            MyPartialClass p = new MyPartialClass();
            p.CallPartialMethod();
            Console.Read();
        }
    }
}
